server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: lovealmighty
    #username: root
    #password: lovealmighty
    #url: jdbc:mysql://localhost:3306/search_engine?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

indexing-settings:
  sites:
    - url: https://dombulgakova.ru/
      name: DOM BULGAKOVA
    - url: https://nikoartgallery.com/
      name: art!

batch:
  page-size: 5
  page-flush-interval-ms: 2000
  lemma-size: 500
  lemma-flush-interval-ms: 1000

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF
    com.zaxxer.hikari: WARN
    searchengine: DEBUG